import { Briefcase, Truck, ShieldCheck, TrendingUp, Landmark } from 'lucide-react';
import { UserPersona } from '../../types';

export const AFRICAN_COUNTRIES = [
  'Algeria',
  'Angola',
  'Benin',
  'Botswana',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cameroon',
  'Central African Republic',
  'Chad',
  'Comoros',
  'DR Congo',
  'Republic of Congo',
  "Cote d'Ivoire",
  'Djibouti',
  'Egypt',
  'Equatorial Guinea',
  'Eritrea',
  'Eswatini',
  'Ethiopia',
  'Gabon',
  'Gambia',
  'Ghana',
  'Guinea',
  'Guinea-Bissau',
  'Kenya',
  'Lesotho',
  'Liberia',
  'Libya',
  'Madagascar',
  'Malawi',
  'Mali',
  'Mauritania',
  'Mauritius',
  'Morocco',
  'Mozambique',
  'Namibia',
  'Niger',
  'Nigeria',
  'Rwanda',
  'Sao Tome and Principe',
  'Senegal',
  'Seychelles',
  'Sierra Leone',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Sudan',
  'Tanzania',
  'Togo',
  'Tunisia',
  'Uganda',
  'Zambia',
  'Zimbabwe',
];

export const ROLES = [
  {
    id: UserPersona.EXPORTER_SME,
    icon: Briefcase,
    label: 'Exporter / Importer',
    desc: 'Trade goods across borders',
  },
  {
    id: UserPersona.LOGISTICS,
    icon: Truck,
    label: 'Logistics Provider',
    desc: 'Move cargo & manage fleets',
  },
  {
    id: UserPersona.BANK,
    icon: Landmark,
    label: 'Bank / Insurer',
    desc: 'Finance & risk management',
  },
  {
    id: UserPersona.CUSTOMS,
    icon: ShieldCheck,
    label: 'Customs / Gov',
    desc: 'Regulatory oversight',
  },
  {
    id: UserPersona.ANALYST,
    icon: TrendingUp,
    label: 'Trade Analyst',
    desc: 'Market data & insights',
  },
];
